### ISSUE TITLE
Include other metrics

### ISSUE THREAD

**Issue by alexmascension** [yanailab/knn-smoothing#14]
Hi!

I've been using your program and seems to do a nice job. Would it be possible to include other metrics apart from euclidean? I usually use cosine, and seems to do a better jobs at cluster identification and dimensionality reduction than euclidean. 

Thanks!

**Comment by Puriney** [comment]
https://github.com/yanailab/knn-smoothing/blob/87132e68a7a85f787743e5124eb5b4cb6e2ce48c/knn_smooth.py#L128

Feel free to change the metric parameter if you are using our Python implementation.
